name: Build Job
on:
  push:
    branches:
      - main

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - name: Code checkout
        uses: actions/checkout@v4

      - name: Maven build
        uses: mvn install

      - name: Upload Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: vprofile-app
          path: target/*.war  

  Testing:
    runs-on: ubuntu-latest
    needs: Build
    steps:
      - name: Code checkout
        uses: actions/checkout@v4

      - name: Run tests on main branch
        uses: mvn test
        
      - name: Checkstyle
        uses: mvn checkstyle:checkstyle  
