name: Download vprofile-app Artifact

on:
  workflow_dispatch:  # Trigger manually from GitHub Actions UI

jobs:
  Download:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download vprofile-app artifact
        uses: actions/download-artifact@v4
        with:
          name: vprofile-app   # Must match the name from your Build workflow
          path: artifact       # Folder where the WAR file will be saved

      - name: List downloaded files
        run: ls -l artifact

      - name: Show WAR file name
        run: |
          echo "Downloaded WAR file(s):"
          find artifact -name "*.war"
