name: Download Build Artifact

on:
  workflow_dispatch:  # Allows you to run this manually from GitHub Actions UI

jobs:
  Download:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download Build Artifact
        uses: actions/download-artifact@v4
        with:
          name: vprofile-app   # must match the name used in the upload step
          path: ./artifact     # location to save the downloaded file(s)

      - name: List downloaded files
        run: ls -l ./artifact

      # Optional: example if you want to deploy or inspect the .war
      - name: Display WAR file name
        run: |
          echo "Downloaded WAR file:"
          find ./artifact -name "*.war"
